### ISSUE TITLE
Error could not find /dev/fb1

### ISSUE THREAD

**Issue by squirticulous** [tingbot/tingbot-os#27]

**Comment by joerick** [comment]
Hey xnoahg! Could you give more context to this error please- what hardware you're running it on, if you have a tingbot, where you are in the setup process, what did you do to get this error?

**Comment by squirticulous** [comment]
I boot up my raspberry pi 3 I do not have the kit I just have a monitor and a raspberry pi 3 I boot up and it says that
Over and over again

**Comment by squirticulous** [comment]
I'm sorry I did not answer in so long maybe y'all fixed it in a new update to the tingbot os on GitHub

**Comment by squirticulous** [comment]
Let me try to update the library

**Comment by squirticulous** [comment]
so guess what a billion years later im coming back to try it again bacause as someone said "if at first you dont suceed try try again"

**Comment by squirticulous** [comment]
i have another question is the .deb so i can put it on a rasbpian thats already configured if so that would be helpful because i have a screen for my Rspberry pi 3 but it requires a already made os with the drivers already installed so can i install the .deb to it with packager on that os to make it run on my screen?

**Comment by joerick** [comment]
Hi. Can't fault you for perseverance! Is the screen you're trying to use a Tingbot screen?

**Comment by squirticulous** [comment]
no im using a 3.5 inch rpi LCD that requires its drivers i did not buy a ting bot becuase i have usd not whatevr kind of money that is

**Comment by squirticulous** [comment]
and now it does not have that error anymore it just does not boot it stays frozen for ever at one screen and then restarts

**Comment by squirticulous** [comment]
it repeats that thanks for any help you can give me over the years i've tried to get this to boot

**Comment by squirticulous** [comment]
hey whats the default password for ssh on the tingbot i need it to install my drivers thankyou have a great day

**Comment by squirticulous** [comment]
can you please answer me joerick im still trying to get this to work and if it dosnt il review it as a zero and say they dont give you any help

**Comment by squirticulous** [comment]
if u need to email me @ xnoahg@gmail.com thankyou

**Comment by joerick** [comment]
If you're using a third party screen it should come with documentation and drivers. You should ask whoever you bought it from. 

This OS is designed to work with the Tingbot hardware. If you want to run it on something else, feel free to try (it's open source!), but you're on your own.

**Comment by squirticulous** [comment]
thanks
