### ISSUE TITLE
Error 1 - No such file or directory

### ISSUE THREAD

**Issue by f0rdfisher** [tingbot/tingbot-os#29]
dpkg -b build/root build/tingbot-os.deb
make: dpkg: No such file or directory
make: *** [build/tingbot-os.deb] Error 1

**Comment by f0rdfisher** [comment]
no comment/solution?

**Comment by joerick** [comment]
Hey @f0rdfisher - looks like you don't have dpkg installed on the machine you're trying to build - for example, if you're on Mac, you could run `brew install dpkg`
