### ISSUE TITLE
Multi OS build compatibility

### ISSUE THREAD

**Issue by Rob4001** [tingbot/tingbot-os#9]
Currently the Makefile utilizes the "ditto" command which is not available on Linux

Potentially changing to a cp or zip command would fix this issue

**Comment by joerick** [comment]
I've changed those calls to zip/unzip in 8d870d65a84c21f43d2e5d90d492cb469aa6ee88

I tried briefly to build it in an Ubuntu VM but booting Raspbian in QEMU didn't complete... not sure why, perhaps differences in expect or QEMU on these platforms?

I'll leave this open until somebody reports a successful build.

**Comment by Rob4001** [comment]
Build now seems to work, 
there are additional build deps for linux namely : expect and qemu-system-arm
as by default the qemu package will only install the native system library

**Comment by joerick** [comment]
What distro are you running @Rob4001?

**Comment by Rob4001** [comment]
Fedora

**Comment by joerick** [comment]
Thanks, got it working on Fedora.

Here are the steps to build on Linux, for reference:

```console
$ sudo yum install expect qemu-system-arm git make zip unzip dpkg python
$ git clone http://github.com/tingbot/tingbot-os
$ cd tingbot-os
$ make
```

Also, it can't be run by root for some reason.
